#!/usr/bin/env bash
#
# convert.sh — regenerate the openstrap_icons WebP assets from raw PNG art.
#
# Usage:
#   tool/convert.sh [SOURCE_DIR]
#
# SOURCE_DIR defaults to $OPENSTRAP_ICON_SRC, then ../openstrap-icons
# (relative to the package root). Source files must be named
# {base}-light.png / {base}-dark.png (any square size; 1024x1024 expected).
#
# Pipeline per file:  sips -Z 512  ->  cwebp -q 90 -alpha_q 100
# Outputs:            assets/{light,dark}/{base}.webp
# Also regenerates:   lib/src/asset_manifest.g.dart (which variants exist)
#
# Re-runnable: drop new PNGs in the source dir, run again, then add the
# matching OsIcon enum member in lib/src/os_icon.dart.

set -euo pipefail

PKG_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SRC_DIR="${1:-${OPENSTRAP_ICON_SRC:-$PKG_DIR/../openstrap-icons}}"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

command -v sips >/dev/null || { echo "sips not found (macOS required)"; exit 1; }
command -v cwebp >/dev/null || { echo "cwebp not found (brew install webp)"; exit 1; }

[ -d "$SRC_DIR" ] || { echo "source dir not found: $SRC_DIR"; exit 1; }

mkdir -p "$PKG_DIR/assets/light" "$PKG_DIR/assets/dark"

light_bases=()
dark_bases=()
total_in=0
total_out=0

echo "source: $SRC_DIR"
echo

for png in "$SRC_DIR"/*.png; do
  [ -e "$png" ] || { echo "no PNGs found in $SRC_DIR"; exit 1; }
  fname="$(basename "$png" .png)"
  case "$fname" in
    *-light) variant="light"; base="${fname%-light}" ;;
    *-dark)  variant="dark";  base="${fname%-dark}"  ;;
    *) echo "SKIP (no -light/-dark suffix): $fname.png"; continue ;;
  esac

  out="$PKG_DIR/assets/$variant/$base.webp"
  tmp="$TMP_DIR/$fname.png"

  sips -Z 512 "$png" --out "$tmp" >/dev/null
  cwebp -quiet -q 90 -alpha_q 100 -m 6 -metadata none "$tmp" -o "$out"

  in_sz=$(stat -f%z "$png")
  out_sz=$(stat -f%z "$out")
  total_in=$((total_in + in_sz))
  total_out=$((total_out + out_sz))
  printf '%-32s %8d -> %7d bytes\n' "$variant/$base.webp" "$in_sz" "$out_sz"

  if [ "$variant" = "light" ]; then light_bases+=("$base"); else dark_bases+=("$base"); fi
done

echo
printf 'TOTAL: %d -> %d bytes (%.1f%% of original)\n' \
  "$total_in" "$total_out" "$(echo "$total_out * 100 / $total_in" | bc -l)"

# --- regenerate the asset manifest -----------------------------------------
manifest="$PKG_DIR/lib/src/asset_manifest.g.dart"
{
  echo "// GENERATED by tool/convert.sh — do not edit by hand."
  echo "// Regenerate by running tool/convert.sh after adding source PNGs."
  echo
  echo "/// Asset base names that have a light-theme variant."
  echo "const Set<String> kLightAssets = {"
  printf '%s\n' "${light_bases[@]}" | sort | sed "s/.*/  '&',/"
  echo "};"
  echo
  echo "/// Asset base names that have a dark-theme variant."
  echo "const Set<String> kDarkAssets = {"
  printf '%s\n' "${dark_bases[@]}" | sort | sed "s/.*/  '&',/"
  echo "};"
} > "$manifest"

echo "manifest: $manifest (${#light_bases[@]} light, ${#dark_bases[@]} dark)"
